services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASS
      - POSTGRES_DB=DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5430"


volumes:
  postgres_data: