"""fixing relationship

Revision ID: 4f27372dc894
Revises: a659a566ecb5
Create Date: 2025-04-11 12:10:53.714105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f27372dc894'
down_revision: Union[str, None] = 'a659a566ecb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'table_id')
    # ### end Alembic commands ###
